apiVersion: skaffold/v2beta28
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./k8s/*
build:
  artifacts:
    - image: nestjs/mantainer
      context: mantainer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'mantainer/scr/**/*.ts'
            dest: .
    - image: nestjs/purchase-orders
      context: purchase-orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'purchase-orders/scr/**/*.ts'
            dest: .
    - image: client-app
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'client/**/*.*'
            dest: .