apiVersion: skaffold/v2beta28
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./k8s/*
build:
  artifacts:
    - image: nestjs/purchase-orders
      context: purchase-orders
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'purchase-orders/scr/**/*.ts'
            dest: .
    - image: nestjs/mantainer
      context: mantainer
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'mantainer/scr/**/*.ts'
            dest: .
    - image: client-app
      context: client
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'client/**/*.*'
            dest: .
profiles:
  - name: prod
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: production
      - op: replace
        path: /build/artifacts/1/docker/target
        value: production
      - op: replace
        path: /build/artifacts/2/docker/target
        value: production