apiVersion: skaffold/v2beta28
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./k8s/*
build:
  artifacts:
    - image: nestjs/mantainer
      context: mantainer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'mantainer/scr/**/*.ts'
            dest: .