apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: "/api/products/?(.*)"
        pathType: Prefix
        backend:
          service:
            name: products-srv
            port:
              number: 3000
      - path: "/api/purchase-orders/?(.*)"
        pathType: Prefix
        backend:
          service:
            name: purchase-orders-srv
            port:
              number: 3000
      - path: "/?(.*)"
        pathType: Prefix
        backend:
          service:
            name: client-srv
            port:
              number: 3000
    